version: '3.0'

services:

  back:
    container_name: back
    build:
      context: ./back
    env_file:
      - .dev.env
    volumes:
      - .:/back/app
      - /back/app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:dev
    depends_on:
        - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .dev.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
